Ext.define('IoTosOmExt.model.common.shiftplanjob.ShiftPlanJob', {
	extend : 'ESVC.model.foundation.dataitem.DataItem',
	fields: [{
      name:'cntrNo'
   },{
      name:'yjobType'
   },{
      name:'orderNo'
   },{
      name:'shiftSeq'
   },{
      name:'pequNo'
   },{
      name:'tequNo'
   },{
      name:'tBlock'
   },{
      name:'tbayIdx'
   },{
      name:'trowIdx'
   },{
      name:'tTier'
   },{
      name:'tArea'
   },{
      name:'remark'
   },{
      name:'odrTime'
   },{
      name:'actualTime'
   },{
      name:'ytNo'
   },{
      name:'transType'
   },{
      name:'cmplYo'
   },{
      name:'cmplYf'
   },{
      name:'groupNo'
   },{
      name:'odrState'
   },{
      name:'vcntrNo'
   },{
      name:'groupId'
   },{
      name:'dumyChk'
   },{
      name:'jobOdrSeq'
   },{
      name:'remark2'
   },{
      name:'fBlock'
   },{
      name:'fbayIdx'
   },{
      name:'frowIdx'
   },{
      name:'fTier'
   },{
      name:'fArea'
   },{
      name:'unlinkChk'
   },{
      name:'cntrId'
   },{
      name:'cntrUid'
   },{
      name:'ptnrType'
   },{
      name:'ptnrCode'
   },{
      name:'staffCd'
   },{
      name:'ittIOMode'
   },{
      name:'vslCd'
   },{
      name:'callYear'
   },{
      name:'callSeq'
   },{
      name:'cntrSeq'
   }]
});