Ext.define('IoTosOmExt.model.import.stowagebayplanlist.SearchStowageBayPlan', {
   extend : 'ESVC.model.foundation.dataitem.DataItem',
   fields: [{
      name:'transInType'
   },{
      name:'reserveType'
   },{
      name:'reserveTypes'
   },{
      name:'vslCd'
   },{
      name:'callYear'
   },{
      name:'callSeq'
   },{
      name:'storageType'
   },{
      name:'cntrNo'
   },{
      name:'userVoy'
   },{
      name:'inLane'
   },{
      name:'ixCd'
   },{
      name:'cntrState'
   },{
      name:'fe'
   },{
      name:'ptnrCode'
   },{
      name:'mode'
   },{
      name:'feCheck',
      type:'boolean'
   },{
      name:'oprCheck',
      type:'boolean'
   },{
      name:'noMessageCheck',
      type:'boolean'
   },{
      name:'modeInValues'
   },{
      name:'searchReserveType'
   },{
      name:'cntrStateInValues'
   }]   
});