Ext.define('IoTosOmExt.model.common.vesselschedule.VesselSchedule', {
	extend : 'ESVC.model.foundation.dataitem.DataItem',
	fields: [{
      name:'eta'
   },{
      name:'etw'
   },{
      name:'etd'
   },{
      name:'longtermEta'
   },{
      name:'longtermEtb'
   },{
      name:'longtermEtd'
   },{
      name:'disQty'
   },{
      name:'loadQty'
   },{
      name:'shiftQty'
   },{
      name:'fieldValue'
   },{
      name:'vslNm'
   },{
      name:'vslLnm'
   },{
      name:'vslCd'
   },{
      name:'vslType1'
   },{
      name:'callYear'
   },{
      name:'callSeq'
   },{
      name:'userVoyage'
   },{
      name:'inLane'
   },{
      name:'outLane'
   },{
      name:'atd'
   },{
      name:'etb'
   },{
      name:'atw'
   },{
      name:'atc'
   },{
      name:'atb'
   },{
      name:'iVoyNo'
   },{
      name:'oVoyNo'
   },{
      name:'operator1'
   },{
      name:'netTon'
   },{
      name:'docClose'
   },{
      name:'iBaplieChk'
   },{
      name:'oBaplieChk'
   },{
      name:'movinsChk'
   },{
      name:'vvd'
   },{
      name:'refNo'
   },{
      name:'folderExtractID'
   },{
      name:'logStatus'
   },{
      name:'closeChk'
   },{
      name:'status'
   },{
      name:'bargeChk'
   },{
      name:'domesticChk'
   },{
      name:'storageType'
   },{
      name:'berthNo'
   },{
      name:'alongSide'
   },{
      name:'yardClose',
      type: 'date',
      dateFormat: 'time'
   },{
      name:'migrationChk'
   },{
      name:'ata'
   },{
      name:'etc'
   }]   
});


