Ext.define('IoTosOmExt.model.operation.hold.SearchHold', {
	extend : 'ESVC.model.foundation.dataitem.DataItem',
   fields: [{
      name:'cntrMode'
   },{
      name:'holdMode'
   },{
      name:'vslCd'
   },{
      name:'callYear'
   },{
      name:'callSeq'
   },{
      name:'userVoy'
   },{
      name:'holdType'
   },{
      name:'holdChk'
   },{
      name:'cntrNo'
   },{
      name:'cntrUid'
   },{
      name:'holdCode'
   },{
      name:'holdCodes'
   },{
      name:'cntrNos'
   },{
      name:'cntrId'
   },{
      name:'jobOdrNo2'
   },{
      name:'blNos'
   },{
      name:'holdCodeList'
   },{
      name:'cntrNoList'
   },{
      name:'jobOdrNo2List'
   },{
      name:'blNoList'
   }]   
});