Ext.define('IoTosOmExt.model.import.manifestlist.ManifestList', {
   extend : 'ESVC.model.foundation.dataitem.DataItem',
   fields: [{
         name:'vslCd'
      },{
         name:'callYear'
      },{
         name:'callSeq'
      },{
         name:'ixCd'
      },{
         name:'soNo'
      },{
         name:'blNo'
      },{
         name:'ptnrCode'
      },{
         name:'por'
      },{
         name:'pol'
      },{
         name:'pod'
      },{
         name:'fpod'
      },{
         name:'fdest'
      },{
         name:'delv'
      },{
         name:'netWgt'
      },{
         name:'wgt'
      },{
         name:'setTempC'
      },{
         name:'setTempF'
      },{
         name:'imdg'
      },{
         name:'unno'
      },{
         name:'forwarder'
      },{
         name:'consignee'
      },{
         name:'commodity'
      },{
         name:'lclFcl'
      },{
         name:'userVoy'
      },{
         name:'houseBlNo'
      },{
         name:'shipper'
      },{
         name:'containerQty'
      },{
         name:'packageQty'
      },{
         name:'packageData'
      },{
         name:'cbm'
      },{
         name:'marksNos'
      },{
         name:'returnPlace'
      },{
         name:'bulkCheck'
      },{
         name:'remark1'
      },{
         name:'remark2'
      },{
         name:'remark3'
      },{
         name:'consigneeEDI'
      },{
         name:'commodityEDI'
      },{
         name:'notifyAddr'
      },{
         name:'vvd'
      },{
         name:'rowLock'
      },{
         name:'lclCount'
      },{
         name:'keyFieldName'
      },{
         name:'consigneeAddr'
      },{
         name:'customsNo'
      },{
         name:'customWgt'
      },{
         name:'customCbm'
      },{
         name:'bondAreaNo'
      },{
         name:'backUpSoNo'
      },{
         name:'backUpBlNo'
      }]
});

