Ext.define('IoTosOmExt.model.common.container.SearchContainer', {
	extend : 'ESVC.model.foundation.dataitem.DataItem',
	fields: [{
      name:'tableName'
   },{
      name:'cntrId'
   },{
      name:'cntrUid'
   },{
      name:'vslCd'
   },{
      name:'callYear'
   },{
      name:'callSeq'
   },{
      name:'prevVsl'
   },{
      name:'prevYear'
   },{
      name:'prevSeq'
   },{
      name:'cntrNo'
   },{
      name:'cntrSeq'
   },{
      name:'rsrvType'
   },{
      name:'rsrvTypes'
   },{
      name:'rsrvSeq'
   },{
      name:'ixCd'
   },{
      name:'ixCds'
   },{
      name:'delv'
   },{
      name:'delvs'
   },{
      name:'cargoType'
   },{
      name:'cargoTypes'
   },{
      name:'cntrState'
   },{
      name:'cntrStates'
   },{
      name:'transType'
   },{
      name:'transType2'
   },{
      name:'notTransType'
   },{
      name:'notTransTypes'
   },{
      name:'notTransType2'
   },{
      name:'notTransTypes2'
   },{
      name:'dispatchMode'
   },{
      name:'dispatchMode2'
   },{
      name:'stuffChk'
   },{
      name:'trnVoy'
   },{
      name:'trnVoy2'
   },{
      name:'blNo'
   },{
      name:'prevCntrId'
   },{
      name:'block'
   },{
      name:'bay'
   },{
      name:'row'
   },{
      name:'tier'
   },{
      name:'rowIdx'
   },{
      name:'bayIdx'
   },{
      name:'checkBundlePacked'
   }]
});