Ext.define('IoTosOmExt.model.common.bargeoperation.BargeOperation', {
	extend : 'IoTosOmExt.model.common.container.BaseContainer',
	fields: [{
      name:'ioMode'
   },{
      name:'equNo'
   },{
      name:'applyCheck'
   },{
      name:'printCheck'
   },{
      name:'exportChk'
   },{
      name:'bVslCd'
   },{
      name:'bCallYear'
   },{
      name:'bCallSeq'
   },{
      name:'bUserVoy'
   },{
      name:'bOutLane'
   },{
      name:'bVVD'
   },{
      name:'vesselAssign'
   },{
      name:'isDelivered'
   },{
      name:'isAfterStacking'
   },{
      name:'mediumType'
   },{
      name:'bargeInMode'
   },{
      name:'jobStatus'
   },{
      name:'isDomesticChk'
   },{
      name:'isTholdChk'
   },{
      name:'nextVsl'
   },{
      name:'nextYear'
   },{
      name:'nextSeq'
   },{
      name:'nextUserVoy'
   },{
      name:'nextVVD'
   },{
      name:'groupSeq'
   },{
      name:'paymentType'
   },{
      name:'payerType'
   },{
      name:'payer'
   },{
      name:'addService'
   },{
      name:'addServiceCodes'
   },{
      name:'regNo'
   }]
});