Ext.define('Aipc.Main.model.authority.User', {
	extend: 'ESVC.model.foundation.dataitem.DataItem',
	fields: [{
		name: 'detailUserId',
		type: 'string'
	},{
		name: 'detailUserName',
		type: 'string'
	},{
		name: 'userLevel',
		type: 'string'
	}, {
		name: 'password',
		type: 'string'
	}, {
		name: 'useYn',
		type: 'string'
	}, {
		name: 'ptnrCode',
		type: 'string'
	}, {
		name: 'ptnrName',
		type: 'string'
	}, {
		name: 'ptnrType',
		type: 'string'
	}, {
		name: 'idNo',
		type: 'string'
	}, {
		name: 'email',
		type: 'string'
	}, {
		name: 'userType',
		type: 'string'
	}, {
		name: 'telNo',
		type: 'string'
	}, {
		name: 'address',
		type: 'string'
	}, {
		name: 'zipCode',
		type: 'string'
	}, {
		name: 'mobileNo',
		type: 'string'
	}, {
		name: 'remark',
		type: 'string'
	}, {
		name: 'expireDate',
		type: 'string'
	}, {
		name: 'lastLogin',
		type: 'string'
	}, {
		name: 'designation',
		type: 'string'
	}, {
		name: 'version',
		type: 'string'
	}, {
		name: 'active',
		type: 'string'
	}, {
		name: 'activeCode',
		type: 'string'
	}, {
		name: 'roleNm',
		type: 'string'
	}]

});