var CONSTANTS = {};
CONSTANTS.ROOT = "/";
CONSTANTS.ROOT_PATH = "/";

//When deploy must be PROD property : PROD, DEV

CONSTANTS.ENV = "DEV";

////Local
CONSTANTS.SERVER_CONTEXT = "/stat";

//Application Code
CONSTANTS.PROJECT_TITLE = "GWCT";
CONSTANTS.SYSTEM_CODE = "GWCT";	//GWCT
CONSTANTS.VERSION = '7.726.0010';


CONSTANTS.LOCALES =[
	{"code":"ko-KR", "codeName":"Korean"}
];


//  CONSTANTS FOR STATISTICS
CONSTANTS.OCCUPANCY_SEPERATE_ATTRIBUTE = 'Y';
CONSTANTS.USE_BERTH_PLAN_CALLING_STORAGE = 'N';
CONSTANTS.VESSEL_SCHEDULE_VISIBLE = 'Y';

CONSTANTS.MODULE = 'Stat';
CONSTANTS.SERVER_DNS = "http://localhost:8081";




/**DO NOT CHANGE ***START***/
CONSTANTS.AUTH_TYPE_LOCAL = "BASIC";
CONSTANTS.AUTH_TYPE_DEPLOY = "SESSION";
CONSTANTS.AUTH_TYPE = CONSTANTS.AUTH_TYPE_LOCAL;		//Local Development Only

 	
////for Microsoft Azure Active Directory
////TSB
CONSTANTS.AZURE_TENANT = "cloudmost.onmicrosoft.com";
CONSTANTS.AZURE_CLIENT_ID = "4c547893-7034-4966-a8fe-962adfd9e5ac";



CONSTANTS.MAIN_HEADER_HEIGHT = 36;
CONSTANTS.MENU_EXPANDED_WIDTH = 200;


////Customer
//CONSTANTS.CUSTOMER = "GWCT";	//Development Mode


/**DO NOT CHANGE ***END***/
