// const yardDefine = {
//   "1A": {
//     maxBay: 10,
//     maxRow: 5,
//     maxTier: 6,
//     ytPos: "S",
//     ytEnter: "S",
//     bayList: {
//       1: {
//         block: "1A",
//         name2: "01",
//         name4: "01_x",
//         index: 1,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [0, 1, 1, 1, 1],
//       },
//       2: {
//         block: "1A",
//         name2: "02",
//         name4: "02_",
//         index: 2,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       3: {
//         block: "1A",
//         name2: "03",
//         name4: "03_",
//         index: 3,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       4: {
//         block: "1A",
//         name2: "04",
//         name4: "04_",
//         index: 4,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       5: {
//         block: "1A",
//         name2: "05",
//         name4: "05_",
//         index: 5,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       6: {
//         block: "1A",
//         name2: "06",
//         name4: "06_",
//         index: 6,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       7: {
//         block: "1A",
//         name2: "07",
//         name4: "07_",
//         index: 7,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       8: {
//         block: "1A",
//         name2: "08",
//         name4: "08_",
//         index: 8,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       9: {
//         block: "1A",
//         name2: "09",
//         name4: "09_",
//         index: 9,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: true,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       10: {
//         block: "1A",
//         name2: "10",
//         name4: "10_",
//         index: 10,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: true,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//     },
//     rowList: {
//       1: {
//         block: "1A",
//         name: "01",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: false,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       2: {
//         block: "1A",
//         name: "02",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: false,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       3: {
//         block: "1A",
//         name: "03",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: false,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       4: {
//         block: "1A",
//         name: "04",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: false,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       5: {
//         block: "1A",
//         name: "05",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: true,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//     },
//   },
//   "2A": {
//     maxBay: 10,
//     maxRow: 5,
//     maxTier: 6,
//     ytPos: "E",
//     ytEnter: "S",
//     bayList: {
//       1: {
//         block: "2A",
//         name2: "01",
//         name4: "01_",
//         index: 1,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       2: {
//         block: "2A",
//         name2: "02",
//         name4: "02_",
//         index: 2,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       3: {
//         block: "2A",
//         name2: "03",
//         name4: "03_",
//         index: 3,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       4: {
//         block: "2A",
//         name2: "04",
//         name4: "04_",
//         index: 4,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       5: {
//         block: "2A",
//         name2: "05",
//         name4: "05_",
//         index: 5,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       6: {
//         block: "2A",
//         name2: "06",
//         name4: "06_",
//         index: 6,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       7: {
//         block: "2A",
//         name2: "07",
//         name4: "07_",
//         index: 7,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       8: {
//         block: "2A",
//         name2: "08",
//         name4: "08_",
//         index: 8,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: false,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       9: {
//         block: "2A",
//         name2: "09",
//         name4: "09_",
//         index: 9,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: true,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       10: {
//         block: "2A",
//         name2: "10",
//         name4: "10_",
//         index: 10,
//         maxTier: 6,
//         accessDir: "", //ACCESS_DIR
//         nosVoid: 2,
//         maxRow: 5,
//         isLocked: true,
//         ex20Chk: "",
//         ex40Chk: "",
//         ex45Chk: "",
//         CPOs: [1, 1, 1, 1, 1],
//       },
//     },
//     rowList: {
//       1: {
//         block: "2A",
//         name: "01",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: false,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       2: {
//         block: "2A",
//         name: "02",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: false,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       3: {
//         block: "2A",
//         name: "03",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: false,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       4: {
//         block: "2A",
//         name: "04",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: false,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//       5: {
//         block: "2A",
//         name: "05",
//         index: 1,
//         maxBay: 10,
//         maxTier: 6,
//         SCDir: "",
//         isLocked: true,
//         CPOs: [1, 1, 1, 1, 1],
//       },
//     },
//   },
// };
