Ext.define('Iotos.model.config.SiteDistribution', {
	extend: 'ESVC.model.foundation.dataitem.DataItem',
    fields: [
        { name: 'siteCode', type: 'auto'},
        { name: 'useLashingMan', type: 'auto'},
        { name: 'useGearBox', type: 'auto'},
        { name: 'useReleaseLocking', type: 'auto'},
        { name: 'validateLashingManForVOR', type: 'auto'},
        { name: 'useContainerQueryLog', type: 'auto'},
        { name: 'useTablePartitioning', type: 'auto'},
        { name: 'useCntrNoOnViewCntrHist', type: 'auto'},
        { name: 'bayNoInterval', type: 'auto'},
        { name: 'showContainerDetailClass', type: 'auto'},
        { name: 'useValidationPtnrCodeOnly', type: 'auto'},
        { name: 'ptnrAdditionalMandatories', type: 'string'},
        { name: 'useTerminalHoldCodeAuthorization', type: 'auto'},
        { name: 'displayVgmControl', type: 'auto'},
        { name: 'showRemarshallingPlanHistory', type: 'auto'},
        { name: 'vorValidatePtnrType', type: 'date' , dateFormat: 'time'},
        { name: 'useFillFpodRelatedbyFdest', type: 'auto'},
        { name: 'useCustomerTrfCodeOnGeneralCode', type: 'auto'},
        { name: 'useHolidayPtnrCode', type: 'auto'},
        { name: 'ptnrCodeMaskRegEx', type: 'string'},
        { name: 'useBillingModule', type: 'auto'},
        { name: 'useCodeUsageOnGeneralCode', type: 'auto'},
        { name: 'updateDgChkUsingVesselSchedule', type: 'auto'},
        { name: 'isValidatePayerForDelete', type: 'auto'},
        { name: 'isUseNewHoldStateHistoryTable', type: 'auto'},
        { name: 'displayPassingDirRowSideSCBlock', type: 'auto'},
        { name: 'displayBillingClassOnGeneralCode', type: 'auto'},
        { name: 'displayStackDaysInsteadOfDirectInfoOnCntrDtl', type: 'auto'},
        { name: 'applyVietnameseRegNoMask', type: 'auto'},
        { name: 'ptnrERPCustomerIDMaskRegEx', type: 'string'},
        { name: 'allowImportVesselDefineConfirmedOnly', type: 'auto'},
        { name: 'allowImportVesselDefineWithDuplicatedLloydNo', type: 'auto'},
        { name: 'showInforMsgImportVesselDefineAfterChangeIMOCode', type: 'auto'},
        { name: 'useCmhForAirvent', type: 'auto'},
        { name: 'allowSpecialCharGeneralCode', type: 'auto'},
        { name: 'ptnrAdditionalRedOnlyItems', type: 'string'},
        { name: 'provideExtendedLaneCodeLength', type: 'auto'},
        { name: 'displayDummyBerthOptional', type: 'auto'},
        { name: 'provideReeferPlugInOutUser', type: 'auto'},
        { name: 'applySingleShippingAgency', type: 'auto'},
        { name: 'displayErpCustomerGroup', type: 'auto'},
        { name: 'applyNumberOnlyRegNoMask', type: 'auto'},
        { name: 'isValidateDuplicatedRegNo', type: 'auto'},
        { name: 'defaultSelectProvidedGnrlTypes', type: 'string'},
        { name: 'displayStaffNameOnContainerHistory', type: 'auto'},
        { name: 'useNewDGSegregation', type: 'auto'},
        { name: 'useNewDGSegregationSG26', type: 'auto'},
        { name: 'vesselOperationReportPrivateReportHandler', type: 'string'},
        { name: 'displayUnitType', type: 'auto'},
        { name: 'useGangIDForVesselOperation', type: 'auto'},
        { name: 'newLayoutAxis', type: 'auto'},
        { name: 'isProvideBillingOprByServiceLane', type: 'auto'},
        { name: 'displayOldVslCdInVesselParticular', type: 'auto'},
        { name: 'isAutoManualLockForVor', type: 'auto'}
    ]
});