Ext.define('Iotos.model.container.CntrDefault', {
	extend: 'ESVC.model.foundation.dataitem.DataItem',
    fields: [
        { name: 'unno', type:'string'},
        { name: 'imdgClass', type:'string'},
        { name: 'packingGrp', type:'string'},
        { name: 'extendSeg', type:'string'},
        { name: 'cargoType', type:'string'},
        { name: 'sztp2', type:'string'},
        { name: 'fe', type:'string'},
        { name: 'sztpIsoType', type:'string'},
        { name: 'sztpIsoCode', type:'string'},
        { name: 'sztpID', type:'string'},
        { name: 'sztpCode', type:'string'},
        { name: 'sztpGroupCode', type:'string'},
        { name: 'sztpLengthCode', type:'string'},
        { name: 'sztpHeightWidthCode', type:'string'},
        { name: 'sztpTypeCode', type:'string'},
        { name: 'cntrNo', type:'string'},
        { name: 'tCntrNo', type:'string'},
        { name: 'cntrPrefix', type:'string'},
        { name: 'tCntrPrefix', type:'string'},
        { name: 'cntrNumber', type:'string'},
        { name: 'tCntrNumber', type:'string'},
        { name: 'storageCode', type:'string'},
        { name: 'ptnrCode', type:'string'},
        { name: 'szTp', type:'string'},
        { name: 'laneCd', type:'string'},
        { name: 'vslCd', type:'string'},
        { name: 'wgt', type:'int'},
        { name: 'sztpTunnel', type:'boolean'},
        { name: 'e20Wgt', type:'number'},
        { name: 'l20Wgt', type:'number'},
        { name: 'm20Wgt', type:'number'},
        { name: 'h20Wgt', type:'number'},
        { name: 'e40Wgt', type:'number'},
        { name: 'l40Wgt', type:'number'},
        { name: 'm40Wgt', type:'number'},
        { name: 'h40Wgt', type:'number'}
    ]
});