Ext.define('IoTosOmExt.model.common.vesselchange.VesselChange', {
	extend : 'IoTosOmExt.model.common.container.BaseContainer',
	
   fields: [{
      name:'nextVsl'
   },{
      name:'nextYear'
   },{
      name:'nextSeq'
   },{
      name:'nextVVD'
   },{
      name:'nextUserVoy'
   }, {
      name:'nextInLane'
   },{
      name:'nextOutLane'
   },{
      name:'nextPod'
   },{
      name:'nextPol'
   },{
      name:'nextFdest'
   },{
      name:'nextIxCd'
   },{
      name:'nextDelv'
   },{
      name:'applyCheck'
   },{
      name:'rollBackCheck'
   },{
      name:'vesselAssign'
   },{
      name:'isNewScheduleBarge'
   },{
      name:'isNewScheduleEmptyVessel'
   },{
      name:'newBargeSchedule'
   },{
      name:'isStorageVessel'
   },{
      name:'isPrevVesselClear'
   },{
      name:'isVesselScheduleConnect'
   },{
      name:'isOutAssignClear'
   },{
      name:'mODE_CHANGE'
   },{
      name:'tRANSHIPMENT_DELV'
   },{
      name:'rEEXPORT_DELV'
   },{
      name:'terminalPort'
   },{
      name:'rEEXPORT_TRANS_Type'
   },{
      name:'nextCntrId'
   },{
      name:'nextCntrUid'
   },{
      name:'staffCd'
   },{
      name:'domesticAutoCheck'
   },{
      name:'isTholdChk'
   },{
      name:'newTransType'
   },{
      name:'newTransType2'
   },{
      name:'newTruckNo'
   },{
      name:'newTruckNo2'
   },{
      name:'jobOdrVvd'
   },{
      name:'isIndependantDgChkForTs'
   }]
});